networks:
  backend-tier:
    external: true
    name: shared_backend

  frontend-tier:
    external: true
    name: shared_frontend

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    env_file:
      - .env
    volumes:
      - ./backend/src/main/resources/dev_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - backend-tier

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    env_file:
      - .env
    networks:
      - backend-tier

  ipfs:
    image: ipfs/go-ipfs
    container_name: ipfs_node
    ports: 
      - "5001:5001"
    volumes:
      - ./ipfs_data:/data/ipfs
    networks:
      - backend-tier

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        BUILD_MODE: development
    restart: always
    container_name: backend
    env_file:
      - .env
    depends_on:
      - mysql
      - mongo
    environment:
      - "SPRING_PROFILES_ACTIVE=server"
    ports:
        - "8081:8081"
    networks:
      - backend-tier

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    restart: always
    container_name: frontend
    depends_on: 
      - backend
    ports:
      - "3000:3000"
    networks:
      - frontend-tier
      - backend-tier