networks:
  backend-tier:
    external: true
    name: shared_backend

  frontend-tier:
    external: true
    name: shared_frontend

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        BUILD_MODE: production
    restart: always
    container_name: backend
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE: server
    ports:
        - "8081:8081"
    networks:
      - backend-tier

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILD_MODE: production
    restart: always
    container_name: frontend
    environment:
      - NODE_ENV=production
    depends_on: 
      - backend
    ports:
      - "3000:3000"
    networks:
      - frontend-tier
      - backend-tier